import { Link } from "@tanstack/react-router";
import { ArrowRight, Check, CircleHelp, Mail, Search, ShieldCheck, Users } from "lucide-react";
import { FormEvent, useState } from "react";
import { Button } from "@/components/ui/button";
import { PublicShell, PageIntro } from "./public-shell";

const workflows = [
 {n:"01",title:"Email intake",copy:"Supplier messages and attachments become structured quote lines without changing how vendors work.",meta:"AgentMail-ready"},
 {n:"02",title:"Market check",copy:"Each material is compared with current public evidence, source freshness, and an honest confidence score.",meta:"Firecrawl-ready"},
 {n:"03",title:"Approval",copy:"Your team sees the variance, assigns the decision, and sends a recorded response from one live board.",meta:"Convex-ready"},
];
export function ProjectsPage(){return <PublicShell><PageIntro eyebrow="PROJECTS" title="The buying work, connected." copy="Explore the operational workflows YARD turns into one clear, accountable system."/><section className="project-list">{workflows.map((w)=><article key={w.n}><span>{w.n}</span><div><small>{w.meta}</small><h2>{w.title}</h2><p>{w.copy}</p><Link to="/dashboard">View in dashboard <ArrowRight/></Link></div></article>)}</section></PublicShell>}
export function PlansPage(){return <PublicShell><PageIntro eyebrow="PLANS" title="Start with the yard you run today." copy="Simple plans built around quote volume, team size, and the level of buying oversight you need."/><section className="plans-grid">{[["SITE","For one active yard","GH₵ 490","1 inbox · 5 teammates · 250 quotes/mo"],["GROUP","For growing operations","GH₵ 1,290","3 inboxes · 20 teammates · 1,000 quotes/mo"],["NETWORK","For multi-yard teams","LET’S TALK","Custom yards · controls · onboarding"]].map((p,i)=><article className={i===1?"is-featured":""} key={p[0]}><span>{p[0]}</span><h2>{p[1]}</h2><strong>{p[2]}</strong><small>{i<2?"per month":"tailored to your operation"}</small><p>{p[3]}</p><Link to="/contact" className="button button--dark">Choose {p[0].toLowerCase()} <ArrowRight/></Link></article>)}</section></PublicShell>}
export function TeamPage(){return <PublicShell><PageIntro eyebrow="TEAM" title="Built close to the work." copy="YARD starts with the practical reality of buying materials in Accra: busy inboxes, moving prices, and decisions that cannot wait."/><section className="team-feature"><div className="team-monogram">HM</div><div><span>FOUNDER & BUILDER</span><h2>Henry Sam Marfo</h2><p>Product direction, systems, and the conviction that useful software should fit the work people already do.</p><div className="team-links"><a href="https://x.com/henrysammarfo" target="_blank" rel="noreferrer">@henrysammarfo</a><a href="https://github.com/henrysammarfo" target="_blank" rel="noreferrer">GitHub</a></div></div></section><section className="principles"><article><Users/><h3>Local first</h3><p>Designed around real Accra yard routines and procurement language.</p></article><article><ShieldCheck/><h3>Evidence over theatre</h3><p>Every recommendation keeps its source, freshness, and confidence visible.</p></article><article><Check/><h3>Everyday useful</h3><p>The product earns its place by making one repeated job materially easier.</p></article></section></PublicShell>}
export function FaqsPage(){const qs=[["Does YARD replace supplier email?","No. Suppliers continue emailing as usual. YARD turns those messages into structured, comparable decisions."],["Are the market prices guaranteed?","No. Sources, timestamps, and confidence remain visible so buyers can judge the evidence."],["Can several staff review a quote?","Yes. Quotes can be assigned, reviewed, approved, rejected, or sent back for more information."],["Is this connected to live services?","This preview uses clearly labeled demo data. The production architecture is integration-ready."],["Can suppliers see internal benchmarks?","No. Supplier views only expose requests, submitted quotes, and their own status history."]];return <PublicShell><PageIntro eyebrow="FAQs" title="Clear answers, before you commit." copy="How YARD handles suppliers, prices, approvals, and the transition from demo to live operations."/><section className="faq-list">{qs.map(([q,a],i)=><details key={q} open={i===0}><summary><span>{String(i+1).padStart(2,'0')}</span>{q}<b>+</b></summary><p>{a}</p></details>)}</section></PublicShell>}
export function ContactPage(){const [sent,setSent]=useState(false);function submit(e:FormEvent){e.preventDefault();setSent(true)}return <PublicShell><PageIntro eyebrow="GET IN TOUCH" title="Bring us your busiest buying day." copy="Tell us how your yard receives quotes today. We’ll show you what the YARD workflow could look like."/><section className="contact-layout"><aside><h2>Accra, Ghana</h2><p>Product demos and pilot conversations are open.</p><a href="mailto:hello@yard.africa"><Mail/> hello@yard.africa</a></aside>{sent?<div className="form-success"><Check/><h2>Message received.</h2><p>Thanks. We’ll get back to you shortly.</p><Button onClick={()=>setSent(false)} variant="outline">Send another</Button></div>:<form className="contact-form" onSubmit={submit}><label>Name<input required name="name" placeholder="Your name"/></label><label>Work email<input required type="email" name="email" placeholder="you@company.com"/></label><label>Yard or company<input name="company" placeholder="Business name"/></label><label>What should we know?<textarea required rows={5} name="message" placeholder="Tell us about your quote workflow"/></label><Button type="submit">Send enquiry <ArrowRight/></Button></form>}</section></PublicShell>}
export function HowItWorksPage(){return <PublicShell><PageIntro eyebrow="HOW IT WORKS" title="Eight seconds from email to evidence." copy="A simple operational loop where every system changes the live buying state."/><section className="project-list">{workflows.map(w=><article key={w.n}><span>{w.n}</span><div><small>{w.meta}</small><h2>{w.title}</h2><p>{w.copy}</p></div></article>)}</section></PublicShell>}
export function AboutPage(){return <PublicShell><PageIntro eyebrow="ABOUT YARD" title="Built for the people keeping materials moving." copy="YARD is an Accra-first procurement product shaped around the inbox, the market, and the decision desk."/><section className="prose-band"><h2>Everyday usefulness over software theatre.</h2><p>Prices move. Quotes arrive in mixed formats. Approvals get buried across calls and chat. YARD creates a live, legible record without asking suppliers to learn a new system.</p></section></PublicShell>}
export function HelpPage(){return <PublicShell><PageIntro eyebrow="HELP CENTRE" title="Find your next step." copy="Practical guides for inbox setup, quote review, market evidence, approvals, and supplier replies."/><section className="help-search"><Search/><input aria-label="Search help" placeholder="Search guides"/></section><section className="principles">{["Getting started","Reviewing a quote","Managing approvals","Supplier access","Market evidence","Account & settings"].map(x=><article key={x}><CircleHelp/><h3>{x}</h3><p>Step-by-step guidance for your YARD workspace.</p></article>)}</section></PublicShell>}
export function HackathonPage(){return <PublicShell><PageIntro eyebrow="CONVEX ALL GAS · BUILD LOG" title="The proof is in the live loop." copy="A transparent build record for mail → crawl → live board, built in Accra for the 22 September 2026 deadline."/><section className="hack-grid"><article><span>ARCHITECTURE</span><h2>AgentMail → Convex parse → Firecrawl price → live board → reply</h2></article><article><span>SUBMISSION SPINE</span><ul><li><Check/>Live convex.site experience</li><li><Check/>Public /hackathon log</li><li><Check/>Open GitHub repository</li><li><Check/>Three-minute demo video</li></ul></article></section></PublicShell>}
export function LegalPage({kind}:{kind:"Security"|"Privacy"|"Terms"}){const copy={Security:"How we plan to protect workspace access, supplier records, and approvals.",Privacy:"How YARD handles account, supplier, and quote information.",Terms:"The terms governing this preview and future use of YARD."}[kind];return <PublicShell><PageIntro eyebrow="TRUST CENTRE" title={kind} copy={copy}/><section className="legal-copy"><p>Last updated 19 September 2026</p><h2>Demo-stage notice</h2><p>This preview uses simulated procurement records and does not process production supplier mail. Live policies will be finalized before production onboarding.</p><h2>Our approach</h2><p>Access is role-based, material decisions retain an audit trail, and source freshness remains visible throughout the workflow.</p><h2>Questions</h2><p>Contact hello@yard.africa for policy or security enquiries.</p></section></PublicShell>}
export function AuthPage(){return <PublicShell><section className="auth-page"><div><span className="eyebrow">DEMO WORKSPACE</span><h1>Enter YARD as your role.</h1><p>No credentials required in this product preview.</p></div><div className="role-grid">{[["Owner","Full oversight and approvals","/dashboard"],["Buyer","Quotes, evidence, and orders","/board"],["Supplier","Requests and quote status","/supplier-portal"]].map(([r,c,to])=><Link to={to} key={r}><span>{r.slice(0,2).toUpperCase()}</span><div><h2>{r}</h2><p>{c}</p></div><ArrowRight/></Link>)}</div></section></PublicShell>}
