/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BoardRouteImport } from './routes/board'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as HackathonRouteImport } from './routes/hackathon'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TeamWorkspaceRouteImport } from './routes/team-workspace'
import { Route as TermsRouteImport } from './routes/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const HackathonRoute = HackathonRouteImport.update({
  id: '/hackathon',
  path: '/hackathon',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamWorkspaceRoute = TeamWorkspaceRouteImport.update({
  id: '/team-workspace',
  path: '/team-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/approvals': typeof ApprovalsRoute
  '/auth': typeof AuthRoute
  '/board': typeof BoardRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faqs': typeof FaqsRoute
  '/hackathon': typeof HackathonRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/inbox': typeof InboxRoute
  '/materials': typeof MaterialsRoute
  '/orders': typeof OrdersRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/team': typeof TeamRoute
  '/team-workspace': typeof TeamWorkspaceRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/approvals': typeof ApprovalsRoute
  '/auth': typeof AuthRoute
  '/board': typeof BoardRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faqs': typeof FaqsRoute
  '/hackathon': typeof HackathonRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/inbox': typeof InboxRoute
  '/materials': typeof MaterialsRoute
  '/orders': typeof OrdersRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/team': typeof TeamRoute
  '/team-workspace': typeof TeamWorkspaceRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/approvals': typeof ApprovalsRoute
  '/auth': typeof AuthRoute
  '/board': typeof BoardRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faqs': typeof FaqsRoute
  '/hackathon': typeof HackathonRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/inbox': typeof InboxRoute
  '/materials': typeof MaterialsRoute
  '/orders': typeof OrdersRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/projects': typeof ProjectsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/team': typeof TeamRoute
  '/team-workspace': typeof TeamWorkspaceRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activity'
    | '/approvals'
    | '/auth'
    | '/board'
    | '/contact'
    | '/dashboard'
    | '/faqs'
    | '/hackathon'
    | '/help'
    | '/how-it-works'
    | '/inbox'
    | '/materials'
    | '/orders'
    | '/plans'
    | '/privacy'
    | '/projects'
    | '/security'
    | '/settings'
    | '/suppliers'
    | '/team'
    | '/team-workspace'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activity'
    | '/approvals'
    | '/auth'
    | '/board'
    | '/contact'
    | '/dashboard'
    | '/faqs'
    | '/hackathon'
    | '/help'
    | '/how-it-works'
    | '/inbox'
    | '/materials'
    | '/orders'
    | '/plans'
    | '/privacy'
    | '/projects'
    | '/security'
    | '/settings'
    | '/suppliers'
    | '/team'
    | '/team-workspace'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activity'
    | '/approvals'
    | '/auth'
    | '/board'
    | '/contact'
    | '/dashboard'
    | '/faqs'
    | '/hackathon'
    | '/help'
    | '/how-it-works'
    | '/inbox'
    | '/materials'
    | '/orders'
    | '/plans'
    | '/privacy'
    | '/projects'
    | '/security'
    | '/settings'
    | '/suppliers'
    | '/team'
    | '/team-workspace'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivityRoute: typeof ActivityRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuthRoute: typeof AuthRoute
  BoardRoute: typeof BoardRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FaqsRoute: typeof FaqsRoute
  HackathonRoute: typeof HackathonRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InboxRoute: typeof InboxRoute
  MaterialsRoute: typeof MaterialsRoute
  OrdersRoute: typeof OrdersRoute
  PlansRoute: typeof PlansRoute
  PrivacyRoute: typeof PrivacyRoute
  ProjectsRoute: typeof ProjectsRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  SuppliersRoute: typeof SuppliersRoute
  TeamRoute: typeof TeamRoute
  TeamWorkspaceRoute: typeof TeamWorkspaceRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackathon': {
      id: '/hackathon'
      path: '/hackathon'
      fullPath: '/hackathon'
      preLoaderRoute: typeof HackathonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-workspace': {
      id: '/team-workspace'
      path: '/team-workspace'
      fullPath: '/team-workspace'
      preLoaderRoute: typeof TeamWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivityRoute: ActivityRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuthRoute: AuthRoute,
  BoardRoute: BoardRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FaqsRoute: FaqsRoute,
  HackathonRoute: HackathonRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  InboxRoute: InboxRoute,
  MaterialsRoute: MaterialsRoute,
  OrdersRoute: OrdersRoute,
  PlansRoute: PlansRoute,
  PrivacyRoute: PrivacyRoute,
  ProjectsRoute: ProjectsRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  SuppliersRoute: SuppliersRoute,
  TeamRoute: TeamRoute,
  TeamWorkspaceRoute: TeamWorkspaceRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
